### ISSUE TITLE
Create top level menu: (Main Navigation)

### ISSUE THREAD

**Issue by iritush** [codeforbtv/wordpress-codforbtv.org#1]
-Home
-Current Projects: Might make sense to start with the content that is in the slide show from the lunch meetings (parent)
Expunge VT (child)
Coutrtbot (child)
Safety Net Resources (child)
This website (child)
Code of conduct
About
Optional if easy to add: upcoming events

**Comment by ksnielsen** [comment]
I added some notes (including questions) to the site map doc on Google Drive based on the current and past versions of the site.
