### ISSUE TITLE
Set up Jetpack

### ISSUE THREAD

**Issue by ksnielsen** [codeforbtv/wordpress-codforbtv.org#26]
Jetpack intended for use as automatic site backup method (if possible in free version).
Otherwise, explore other options.

**Comment by iritush** [comment]
Jetpack is now set with a Wordpress.com account: c4btvaccounts@codeforbtv.org. I wasn't able to find the free backup option so sending over to you, @annima24 . Thanks!

**Comment by ksnielsen** [comment]
Using another method for backup, but leaving Jetpack set up as is for other features.
