### ISSUE TITLE
Choose a wordpress theme:

### ISSUE THREAD

**Issue by iritush** [codeforbtv/wordpress-codforbtv.org#3]
- Free
- Reliable (widely used and supported)
- Light weight
- Allows the use of own logo, color scheme

**Comment by ksnielsen** [comment]
This is Kirsten. I'll take this task, but I think I need to be added to the organization as a contributor first.
Thanks!

**Comment by ksnielsen** [comment]
Found these free themes by themeisle that fit our criteria: https://themeisle.com/wordpress-themes/free/
I think the Neve theme will fit better of the two (more lightweight): https://themeisle.com/themes/neve/
I will upload Neve into the BTV Wordpress and check it out (without making it live).

**Comment by ksnielsen** [comment]
Neve installed successfully, and I also created a child theme (neve-child), which also installed successfully. Neither have been customized yet for the site, so they're both inactive.

**Comment by ksnielsen** [comment]
Neve has been agreed upon, as well as using the parent outright instead of using a child theme.
