### ISSUE TITLE
Fix DNS - "www.codeforbtv.org" is fine, but "codeforbtv.org" shows an error page. This is a problem with DNS, probably, although it could be a misconfiguration at Dreamhost...

### ISSUE THREAD

**Issue by iritush** [codeforbtv/wordpress-codforbtv.org#5]

**Comment by iritush** [comment]
Looks like some more configuration is needed on the registrar end for the domain:
<img width="1631" alt="Screen Shot 2021-01-27 at 5 28 35 PM" src="https://user-images.githubusercontent.com/35077819/106062818-51ac4400-60c5-11eb-8246-36d013d80d56.png">
<img width="1651" alt="Screen Shot 2021-01-27 at 5 31 18 PM" src="https://user-images.githubusercontent.com/35077819/106063006-8f10d180-60c5-11eb-9cc7-9ce31bbc55a5.png">

**Comment by nfloersch** [comment]
Updated some records at Namecheap.

Old DNS looked like this - with website A records pointing to old site.
![Old DNS](https://user-images.githubusercontent.com/4584739/106166216-ed878f80-6159-11eb-9c72-cac732a978e7.png)


New DNS has removed those and using a CName to redirect bare domain requests to www.codeforbtv.org
![New DNS](https://user-images.githubusercontent.com/4584739/106166228-f11b1680-6159-11eb-9501-3d006225ce7b.png)

**Comment by iritush** [comment]
This appears to be fixed. Records are showing dreamiest now
