### ISSUE TITLE
Archived News 

### ISSUE THREAD

**Issue by annima24** [codeforbtv/wordpress-codforbtv.org#53]
Create a place where older news articles can live.

**Comment by ksnielsen** [comment]
Consider including this article on ExpungeVT: https://codeforamerica.org/news/volunteer-spotlight-delivering-justice-at-scale/

**Comment by ksnielsen** [comment]
New design drafted at https://codeforbtv.org/news-2/ (currently private). @nfloersch, @iritush is this design ready to go live?

**Comment by iritush** [comment]
Looks good to me!

**Comment by ksnielsen** [comment]
Changed former News Feed page slug from `news` to `newsfeed`.
Changed News page slug from `news-2` to `news` before going public and updating in menu.
