### ISSUE TITLE
Add Code for America logo to the footer

### ISSUE THREAD

**Issue by annima24** [codeforbtv/wordpress-codforbtv.org#55]

**Comment by ksnielsen** [comment]
@nfloersch or @iritush: is the latest footer version in the website channel good to be applied site-wide?

**Comment by iritush** [comment]
@ksnielsen can you re-share here? I couldn't find it

**Comment by ksnielsen** [comment]
Got approval from iritush via Slack and nfloersch verbally to apply footer site-wide.
