### ISSUE TITLE
Choose static landing page template

### ISSUE THREAD

**Issue by ksnielsen** [codeforbtv/wordpress-codforbtv.org#7]
- Try to make similar to Neve theme
- Look for one without a menu since not needed

**Comment by ksnielsen** [comment]
- [ ] look at https://pixelarity.com/ for possible templates

**Comment by ksnielsen** [comment]
Templates in order of Kirsten's preference:

1. https://pixelarity.com/items/demos/read-only/green/index.html
2. https://pixelarity.com/items/demos/tessellate/light/index.html
3. https://pixelarity.com/items/demos/visualize/cyan/index.html
4. https://pixelarity.com/items/demos/telephasic/blue/no-sidebar.html

**Comment by iritush** [comment]
We ended up using the CMP - Coming Soon & Maintenance Plugin to create the landing page.
